#!/bin/bash
# BossHunter macOS launcher installer.
# Double-click this file in Finder (or run it in a terminal) to create a
# `BossHunter.command` file on the Desktop. Double-clicking that Desktop file
# later starts the dedicated Chrome profile and the local workbench together.
#
# Mirrors scripts/windows/install_desktop_shortcut.ps1. Uses repository-relative
# paths only; stores no API keys, passwords, or platform credentials.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAUNCHER="$SCRIPT_DIR/start_bosshunter.sh"
DESKTOP="$HOME/Desktop"
COMMAND_FILE="$DESKTOP/BossHunter.command"

if [ ! -f "$LAUNCHER" ]; then
	echo "[BossHunter] Launcher script not found: $LAUNCHER" >&2
	read -r -p "Press Enter to exit..." _
	exit 1
fi

# Terminal executes *.command files in a shell, so a small stub pointing at the
# repository-relative launcher is enough for a double-click start.
cat > "$COMMAND_FILE" <<EOF
#!/bin/bash
# Generated by scripts/macos/install_launcher.command — do not edit by hand.
exec "$LAUNCHER" "\$@"
EOF
chmod +x "$COMMAND_FILE"

# If the repository was downloaded from the internet, macOS quarantine can
# block the scripts on first run. Clear it for our own launcher pair.
xattr -d com.apple.quarantine "$LAUNCHER" 2>/dev/null || true
xattr -d com.apple.quarantine "$COMMAND_FILE" 2>/dev/null || true

echo "[BossHunter] Created double-click launcher: $COMMAND_FILE"
echo "[BossHunter] Double-click it anytime to open the BossHunter workbench with its dedicated Chrome profile."
read -r -p "Press Enter to close this window..." _
